---
# tasks file for LoadBalancer

  - name : Install Haproxy
    package :
      name : haproxy
      state : present
  - name : see groups
    debug :
      var : groups
  - name : Modify conf file
    template :
      src : haproxy_templ.j2
      dest : /etc/haproxy/haproxy.cfg
    notify : restart_haproxy
  - name : Allow SELinux for Haproxy
    seboolean:
      name: haproxy_connect_any
      state: yes
      persistent: yes
  - name : Add masquerade to public zone
    firewalld :
      masquerade : yes
      zone : public
      permanent : true
      immediate : true
      state : enabled
  - name : Add port to firewall
    firewalld :
      port : "{{bind_port}}/tcp"
      zone : public
      permanent : true
      immediate : true
      state : enabled
  - name : Start service
    service :
      name : haproxy
      state : started
